// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260130124114_CleanTradeHistory")]
    partial class CleanTradeHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("API.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AvailableCash")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Equity")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InitialBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("API.Models.MarketModeEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MarketModes", (string)null);
                });

            modelBuilder.Entity("API.Models.PaperTrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Confidence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EntryPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ExitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InvestAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PnL")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PnLPercent")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PositionSize")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reasons")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StopLoss")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TakeProfit")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OpenedAt");

                    b.HasIndex("Status");

                    b.HasIndex("Symbol");

                    b.ToTable("PaperTrades");
                });

            modelBuilder.Entity("API.Models.RiskSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoTradeEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AutoTradeMaxConcurrent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AutoTradeMinConfidence")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AutoTradeRiskPercent")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefaultRiskPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaxCapitalPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaxRiskPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinRiskRewardRatio")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("SelectedTimeframe")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RiskSettings");
                });

            modelBuilder.Entity("API.Models.ScenarioConfigEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivePreset")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ScenarioConfigs");
                });

            modelBuilder.Entity("API.Models.SimulationSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DriftScale")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FatTailMaxSize")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FatTailMinSize")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FatTailMultiplier")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HighLowRangeMultiplier")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LiveTickNoise")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaxReturnPerBar")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MeanReversionStrength")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PatternOverlayStrength")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("VolatilityScale")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SimulationSettings");
                });

            modelBuilder.Entity("API.Models.TradeHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Confidence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("EntryPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExitReason")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InvestAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsWinner")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PnL")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PnLPercent")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PositionSize")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("StopLoss")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TakeProfit")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClosedAt");

                    b.HasIndex("IsWinner");

                    b.HasIndex("Symbol");

                    b.ToTable("TradeHistory");
                });

            modelBuilder.Entity("API.Models.WatchlistSymbol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("WatchlistSymbols");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "SAP",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "SAP.DE"
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "Siemens",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "SIE.DE"
                        },
                        new
                        {
                            Id = 3,
                            CompanyName = "Allianz",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "ALV.DE"
                        },
                        new
                        {
                            Id = 4,
                            CompanyName = "BASF",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "BAS.DE"
                        },
                        new
                        {
                            Id = 5,
                            CompanyName = "Infineon",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "IFX.DE"
                        },
                        new
                        {
                            Id = 6,
                            CompanyName = "BMW",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "BMW.DE"
                        },
                        new
                        {
                            Id = 7,
                            CompanyName = "Mercedes-Benz",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "MBG.DE"
                        },
                        new
                        {
                            Id = 8,
                            CompanyName = "Volkswagen",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "VOW3.DE"
                        },
                        new
                        {
                            Id = 9,
                            CompanyName = "Dt. Telekom",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "DTE.DE"
                        },
                        new
                        {
                            Id = 10,
                            CompanyName = "RWE",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "RWE.DE"
                        },
                        new
                        {
                            Id = 11,
                            CompanyName = "E.ON",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "EOAN.DE"
                        },
                        new
                        {
                            Id = 12,
                            CompanyName = "Munich Re",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "MUV2.DE"
                        },
                        new
                        {
                            Id = 13,
                            CompanyName = "Commerzbank",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "CBK.DE"
                        },
                        new
                        {
                            Id = 14,
                            CompanyName = "Deutsche Bank",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "DBK.DE"
                        },
                        new
                        {
                            Id = 15,
                            CompanyName = "Siemens Energy",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "ENR.DE"
                        },
                        new
                        {
                            Id = 16,
                            CompanyName = "Adidas",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "ADS.DE"
                        },
                        new
                        {
                            Id = 17,
                            CompanyName = "Bayer",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "BAYN.DE"
                        },
                        new
                        {
                            Id = 18,
                            CompanyName = "Heidelberg Mat.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "HEI.DE"
                        },
                        new
                        {
                            Id = 19,
                            CompanyName = "Zalando",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "ZAL.DE"
                        },
                        new
                        {
                            Id = 20,
                            CompanyName = "Dt. Börse",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "DB1.DE"
                        },
                        new
                        {
                            Id = 21,
                            CompanyName = "Rheinmetall",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "RHM.DE"
                        },
                        new
                        {
                            Id = 22,
                            CompanyName = "MTU Aero",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "MTX.DE"
                        },
                        new
                        {
                            Id = 23,
                            CompanyName = "Airbus",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "AIR.DE"
                        },
                        new
                        {
                            Id = 24,
                            CompanyName = "Sartorius",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "SRT3.DE"
                        },
                        new
                        {
                            Id = 25,
                            CompanyName = "Symrise",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "SY1.DE"
                        },
                        new
                        {
                            Id = 26,
                            CompanyName = "Henkel",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "HEN3.DE"
                        },
                        new
                        {
                            Id = 27,
                            CompanyName = "Covestro",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "1COV.DE"
                        },
                        new
                        {
                            Id = 28,
                            CompanyName = "Porsche AG",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "P911.DE"
                        },
                        new
                        {
                            Id = 29,
                            CompanyName = "Vonovia",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "VNA.DE"
                        },
                        new
                        {
                            Id = 30,
                            CompanyName = "Fresenius",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "FRE.DE"
                        },
                        new
                        {
                            Id = 31,
                            CompanyName = "HelloFresh",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "HFG.DE"
                        },
                        new
                        {
                            Id = 32,
                            CompanyName = "Delivery Hero",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "DHER.DE"
                        },
                        new
                        {
                            Id = 33,
                            CompanyName = "Beiersdorf",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "BEI.DE"
                        },
                        new
                        {
                            Id = 34,
                            CompanyName = "Hannover Rück",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "HNR1.DE"
                        },
                        new
                        {
                            Id = 35,
                            CompanyName = "Brenntag",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "BNR.DE"
                        },
                        new
                        {
                            Id = 36,
                            CompanyName = "Siemens Health.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "SHL.DE"
                        },
                        new
                        {
                            Id = 37,
                            CompanyName = "Fresenius MC",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "FME.DE"
                        },
                        new
                        {
                            Id = 38,
                            CompanyName = "Merck KGaA",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "MRK.DE"
                        },
                        new
                        {
                            Id = 39,
                            CompanyName = "Qiagen",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "QIA.DE"
                        },
                        new
                        {
                            Id = 40,
                            CompanyName = "Porsche SE",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "PAH3.DE"
                        },
                        new
                        {
                            Id = 41,
                            CompanyName = "TeamViewer",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "TMV.DE"
                        },
                        new
                        {
                            Id = 42,
                            CompanyName = "Aixtron",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "AIXA.DE"
                        },
                        new
                        {
                            Id = 43,
                            CompanyName = "SMA Solar",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "S92.DE"
                        },
                        new
                        {
                            Id = 44,
                            CompanyName = "Evotec",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "EVT.DE"
                        },
                        new
                        {
                            Id = 45,
                            CompanyName = "Carl Zeiss",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "AFX.DE"
                        },
                        new
                        {
                            Id = 46,
                            CompanyName = "Nemetschek",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "NEM.DE"
                        },
                        new
                        {
                            Id = 47,
                            CompanyName = "Siltronic",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "WAF.DE"
                        },
                        new
                        {
                            Id = 48,
                            CompanyName = "Jenoptik",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "JEN.DE"
                        },
                        new
                        {
                            Id = 49,
                            CompanyName = "Cancom",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "COK.DE"
                        },
                        new
                        {
                            Id = 50,
                            CompanyName = "GFT Tech",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "GFT.DE"
                        },
                        new
                        {
                            Id = 51,
                            CompanyName = "Nagarro",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "NA9.DE"
                        },
                        new
                        {
                            Id = 52,
                            CompanyName = "Süss MicroTec",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "SMHN.DE"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
